jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        server-id: sonatype-nexus-snapshots
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      env:
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: Build with Maven and Gradle
      run: "./mvnw -B -Dhttps.protocols=TLSv1.2 verify --file pom.xml\nexport MY_JAVA_VERSION=`java\
        \ -version 2>&1 | head -1 | cut -d'\"' -f2 | sed '/^1\\./s///' | cut -d'.'\
        \ -f1`\necho \"JAVA VERSION\" ${MY_JAVA_VERSION}\nif [[ ${MY_JAVA_VERSION}\
        \ == \"11\" ]];\nthen\n  export MY_POM_VERSION=`./mvnw -q -Dexec.executable=\"\
        echo\" -Dexec.args='${projects.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec`\n\
        \  echo \"POM VERSION\" ${MY_POM_VERSION}\n  if [[ $MY_POM_VERSION =~ ^.*SNAPSHOT$\
        \ ]];\n  then\n      ./mvnw -B -Dhttps.protocols=TLSv1.2 clean deploy\n  else\n\
        \      echo \"not deploying release: \" ${MY_POM_VERSION}\n  fi\nelse\n  echo\
        \ \"not deploying on java version: \" ${MY_JAVA_VERSION}\nfi\n"
    strategy:
      matrix:
        java:
        - 11
        - 17
name: Build Test Deploy 1.5
on:
  repository_dispatch:
    types: trigger-ga___maven-v1.yml
